Complete HTML Forms exercise.
dennis-pnguyen/c0723-code-solutions pull request #22
Opened 2023-07-18 18:53 UTC by dennis-pnguyen

<img width="1437" alt="Screenshot 2023-07-18 at 11 52 12 AM" src="https://github.com/dennis-pnguyen/c0723-code-solutions/assets/122412863/90337dc2-587c-42e4-884e-8baf9e1baf48">

2023-07-18 22:01 UTC, shawnkost requested changes
Some changes requested here Dennis!

2023-07-18 22:01 UTC, shawnkost commented on html-forms/index.html
> +        <label for="email">
The "email" text should be inside the `label`. The `p` isn't needed

2023-07-18 22:01 UTC, shawnkost commented on html-forms/index.html
> +            type="text"
This should be `type="email"`

2023-07-18 22:01 UTC, shawnkost commented on html-forms/index.html
> +        <p class="coding">Why is coding cool?</p>
This should be a `label`

2023-07-18 22:01 UTC, shawnkost commented on html-forms/index.html
> +          <option>Because it's powerful</option>
These need a `value` attribute

2023-07-18 22:01 UTC, shawnkost commented on html-forms/index.html
> +        <p class="comment">Comments</p>
This should be a `label`

2023-07-19 20:51 UTC, dennis-pnguyen commented
Updated!

2023-07-19 21:10 UTC, shawnkost requested changes
Couple changes here Dennis!

2023-07-19 21:10 UTC, shawnkost commented on html-forms/index.html
> +          <select id="coding" name="codingiscool">
The `for` needs to either be "coding", or the `id` needs to be "whycoding". The `for `matches the `id`

2023-07-19 21:10 UTC, shawnkost commented on html-forms/index.html
>            <textarea cols="30" rows="8"></textarea>
This needs an `id` to link to the `label` above ^

2023-07-19 21:25 UTC, shawnkost approved these changes
👍🏻

2023-07-19 21:26 UTC, merged