Complete CSS Layout Classes exercise.
dennis-pnguyen/c0723-code-solutions pull request #31
Opened 2023-07-20 23:23 UTC by dennis-pnguyen

![Screenshot 2023-07-20 at 4 15 55 PM](https://github.com/dennis-pnguyen/c0723-code-solutions/assets/122412863/56f329f8-86be-4d32-bac1-092b8685d46e)

2023-07-20 23:38 UTC, shawnkost requested changes
Some changes here Dennis!

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <header>
If you're going to use a `header` here, you should remove the `div` and give the `column-full` class to the `header`

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/kirby.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/fox.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/pikachu.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/ness.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/dk.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          <img src="images/mario.png" />
Needs an `alt` attribute

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +  margin: 0, auto;
This syntax is incorrect. There should be no commas. It should just be `margin: 0 auto`

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +  flex-basis: 100%;
`flex-basis` is a child property, so it doesn't get applied to flex parents. This has no impact, so it should be removed

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
Missing a selector for `column-one-fourth`

2023-07-20 23:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
Missing a selector for `column-full`

2023-07-20 23:48 UTC, dennis-pnguyen commented
Added alt attributes and removed initial div

2023-07-21 17:20 UTC, shawnkost approved these changes
👍🏻

2023-07-21 18:45 UTC, merged