Complete three column layout challenge v1.
dennis-pnguyen/c0723-code-solutions pull request #35
Opened 2023-07-22 23:51 UTC by dennis-pnguyen

<img width="1440" alt="Screenshot 2023-07-22 at 4 46 12 PM" src="https://github.com/dennis-pnguyen/c0723-code-solutions/assets/122412863/9625dead-1ec6-40b4-883f-81302cd3e0c2">

2023-07-24 16:40 UTC, shawnkost requested changes
Few tweaks here Dennis! Also one other thing I noticed

1. There should be less space in-between the text underneath your image. Your "Streamlined QMS" & the paragraph text underneath it for example. Compare your page to our example image. Ours has the text closer together

2023-07-24 16:40 UTC, shawnkost commented on css-three-column-layout/index.html
> +</div--->
Delete all old code

2023-07-24 16:40 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  padding-bottom: 25px;
If you're using this to add space between the `h2` and the content below, you should be using `margin-bottom` instead. `margin` is used to add space between elements

2023-07-24 16:40 UTC, shawnkost commented on css-three-column-layout/styles.css
> +}
You're immediately overriding these styles right below this on lines 45 - 51. If none of these styles are being applied, why include them?

2023-07-25 11:41 UTC, dennis-pnguyen commented
<img width="852" alt="Screenshot 2023-07-24 at 9 26 10 PM" src="https://github.com/dennis-pnguyen/c0723-code-solutions/assets/122412863/d7535a67-448f-4ea9-8db6-ecde51e8750d">

2023-07-25 16:55 UTC, shawnkost approved these changes
👍🏻

2023-07-25 17:46 UTC, merged